name: growth-hub release
on:
 push:
   branches:
     - main
     - '*.x'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.0
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          cache: pnpm
      - run: pnpm i
      - uses: mansagroup/nrwl-nx-action@v3.2.1
        with:
          targets: lint
          nxCloud: 'true'
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{secrets.NX_CLOUD_ACCESS_TOKEN}}
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.0
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          cache: pnpm
      - run: pnpm i
      - uses: mansagroup/nrwl-nx-action@v3.2.1
        with:
          targets: test
          nxCloud: 'true'
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{secrets.NX_CLOUD_ACCESS_TOKEN}}
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.0
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          cache: pnpm
      - run: pnpm i
      - name: Build affected
        uses: mansagroup/nrwl-nx-action@v3.2.1
        with:
          targets: build
          args: --configuration=production
          nxCloud: 'true'
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{secrets.NX_CLOUD_ACCESS_TOKEN}}
      - name: Save build output
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: dist/packages

  release:
    needs:
      - lint
      - test
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.0
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          cache: pnpm
      - run: pnpm i
      - name: Get build output
        continue-on-error: true
        uses: actions/download-artifact@v2
        with:
          name: packages
          path: dist/packages
      - name: Release affected
        uses: mansagroup/nrwl-nx-action@v3.2.1
        with:
          targets: release
          nxCloud: 'true'
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{secrets.NX_CLOUD_ACCESS_TOKEN}}
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_BOT_GITHUB_PAT }}